### ISSUE TITLE
DoxBox minimize on start doesn't work as expected

### ISSUE THREAD

**Issue by Ralkniv** [t-d-k/LibreCrypt#16]
When selecting option "minimize on start" the program loads to systray but also to taskbar and has to be fully minimized to systray only manually. This worked OK in the last FOTFE version.

Also - DoxBox Explorer fails to open a FOTFE volume and returns error "Division by zero".

Also - DoxBox Explorer on update check checks version (1.00) but finds latest version 6.00, which is obviously DoxBox latest version, not the DoxBox Explorer's...

Tested in Win7x86  Ent SP1.

The last idea for improvement is the text at the status bar when hovering mouse: the caption should perhaps be disabled on hover over status bar as it shows this unnicely and also the http link format should be pruned of unnecessary technicals A HREF=...

![db_snapshot](https://cloud.githubusercontent.com/assets/6896690/6752526/9fd07c80-cf0f-11e4-9685-fbe2de28e76e.jpg)

The same goes for DoxBox Explorer.

**Comment by Ralkniv** [comment]
Also correct the typo in Options, Tab System Tray, Mimimise change to Minimise.

**Comment by Ralkniv** [comment]
Correct the typo in Options, System Tray tab - Mimimise change to minimize.

Also please remove the text "This software is based on..." as it looks really ugly; consider placing it in the About box. Moreover, the FOTFE web link is dead for few years already so it's rather misleading...

**Comment by t-d-k** [comment]
Thanks for these very useful bug reports, 
1. Re: the minimise issue: standard windows behaviour is to show minimised apps in the taskbar. The systray is for 'background' apps, and there is an option for doxbox to minimise to the systray - is this checked for you? There are several bugs to do with starting when Windows starts which will likely get fixed for 6.2.
2. The div-by-zero error is difficult to reproduce, but I think it is fixed for 6.1. Let me know if it recurs after the release. 
3. The version number bug has been fixed for 6.1, and the 'mimimise' typo.
4. So far as the text is concerned, unfortunately this is a condition of the FreeOTFE licence. It could possibly be replaced with a splash screen, but that would be more intrusive. The exact text is specified by the licence, so I can't change it. I will change the status bar text though.
5. There are no plans to remove compatibility with the PDA version. but compatibility with older versions of FreeOTFE (before 5.21) will be removed.
6. The 'T' means it was opened with a PKCS11 token - but it probably wasn't, and this is a bug which is fixed in 6.1.
7. The 6.1 release is coming soon.
cheers
tdk

**Comment by Ralkniv** [comment]
>> The systray is for 'background' apps, and there is an option for doxbox to minimise to the systray - is this checked for you?...

I use this feature but it still loads the prog also to the taskbar. If I run with the same setting FOTFE, it get cleanly minimized to systray only. Pls, this is indeed a bug in DoxBox...

>> The div-by-zero error is difficult to reproduce, but I think it is fixed for 6.1. Let me know if it recurs after the release...

I noticed that this error appears when attempting to open a container with a non-FAT* filesystem (NTFS, exFAT) in the DoxBox Explorer. When I reformatted this container to FAT it then opened cleanly. But I guess this limitation of DB Explorer is pretty much limiting as it cannot open in it anything what is not on a FAT filesystem (and what is nowadays...?:-))

>> 4. So far as the text is concerned, unfortunately this is a condition of the FreeOTFE licence. It could possibly be replaced with a splash screen, but that would be more intrusive. The exact text is specified by the licence, so I can't change it. I will change the status bar text though.

Pls, do not add a splash screen (unless you allow optionally not to show it in the settings...). This is a much worse solution.

>> The 'T' means it was opened with a PKCS11 token - but it probably wasn't, and this is a bug which is fixed in 6.1.      

I do not use tokens so I guess it is a bug. Moreover, it doesn't show with some file containers whilst it does with some others. No clear common denominator why so, though.

And what is soon?:-) Soon we shall be flying to Mars...:-)))))

Best regards:-)

**Comment by t-d-k** [comment]
The minimise to tray problems are all fixed now.
